List<Map<String, String>> unitNames = [
  {"Türk Lirası": "TRY"},
  {"BAE Dirhemi": "AED"},
  {"Afgan Afganisi": "AFN"},
  {"Arnavutluk Leki": "ALL"},
  {"Ermenistan Dramı": "AMD"},
  {"Hollanda Ant. Gul.": "ANG"},
  {"Angola Kwanzası": "AOA"},
  {"Arjantin Pesosu": "ARS"},
  {"Avustralya Doları": "AUD"},
  {"Aruba Florini": "AWG"},
  {"Azerbaycan Manatı": "AZN"},
  {"Bosna-Hersek Markı": "BAM"},
  {"Barbados Doları": "BBD"},
  {"Bangladeş takası": "BDT"},
  {"Bulgar Levası": "BGN"},
  {"Bahreyn Dinarı": "BHD"},
  {"Burundi Frangı": "BIF"},
  {"Bermuda Doları": "BMD"},
  {"Brunei Doları": "BND"},
  {"Bolivya Bolivianosu": "BOB"},
  {"Brezilya Reali": "BRL"},
  {"Bahama Doları": "BSD"},
  {"Bhutan Ngultrumu": "BTN"},
  {"Botsvana Pulası": "BWP"},
  {"Beyaz Rusya Rublesi": "BYN"},
  {"Belize Doları": "BZD"},
  {"Kanada Doları": "CAD"},
  {"Kongo Frangı": "CDF"},
  {"İsviçre Frangı": "CHF"},
  {"Şili Pesosu": "CLP"},
  {"Çin Yuanı": "CNY"},
  {"Kolombiya Pesosu": "COP"},
  {"Kosta Rika Kolonu": "CRC"},
  {"Küba Pesosu": "CUP"},
  {"Yeşil Burun Ada. Esku": "CVE"},
  {"Çek Korunası": "CZK"},
  {"Cibuti Frangı": "DJF"},
  {"Danimarka Kronu": "DKK"},
  {"Dominik Pesosu": "DOP"},
  {"Cezayir Dinarı": "DZD"},
  {"Mısır Lirası": "EGP"},
  {"Eritre Nafkası": "ERN"},
  {"Etiyopya Birri": "ETB"},
  {"Euro": "EUR"},
  {"Fiji Doları": "FJD"},
  {"Falkand Adası Pound": "FKP"},
  {"Faroese Krona": "FOK"},
  {"İngiliz Sterlini": "GBP"},
  {"Gürcisten Lirası": "GEL"},
  {"Guernsey Pound": "GGP"},
  {"Gana Cedisi": "GHS"},
  {"Gibraltlar Pound": "GIP"},
  {"Gambiya Delasisi": "GMD"},
  {"Gine Frangı": "GNF"},
  {"Guatemala Quetzalı": "GTQ"},
  {"Guyana Doları": "GYD"},
  {"Hong Kong Doları": "HKD"},
  {"Honduras Lempirası": "HNL"},
  {"Hırvat Kunası": "HRK"},
  {"Haiti Gourdesi": "HTG"},
  {"Macar Forinti": "HUF"},
  {"Endonezya Rupisi": "IDR"},
  {"Yeni İsrail Şekeli": "ILS"},
  {"Man Adası Pound": "IMP"},
  {"Hindistan Rupisi": "INR"},
  {"Irak Dinarı": "IQD"},
  {"İran Riyali": "IRR"},
  {"İzlanda Kronu": "ISK"},
  {"Jersey Pound": "JEP"},
  {"Jamakia Doları": "JMD"},
  {"Ürdün Dinarı": "JOD"},
  {"Japon Yeni": "JPY"},
  {"Kenya Şilini": "KES"},
  {"Kırgızistan Somu": "KGS"},
  {"Kamboçya Rieli": "KHR"},
  {"Kleverkid Coin": "KID"},
  {"Komor Frangı": "KMF"},
  {"Güney Kore Wonu": "KRW"},
  {"Kuveyt Dinarı": "KWD"},
  {"Cayman Adaları Doları": "KYD"},
  {"Kazakistan Tengesi": "KZT"},
  {"Laos Kipi": "LAK"},
  {"Lübnan Lirası": "LBP"},
  {"Sri Lanka Rupisi": "LKR"},
  {"Liberya Doları": "LRD"},
  {"Lesoto Lotisi": "LSL"},
  {"Libya Dinarı": "LYD"},
  {"Fas Dirhemi": "MAD"},
  {"Moldova Leyi": "MDL"},
  {"Madagaskar Ariarisi": "MGA"},
  {"Makedonya Dinarı": "MKD"},
  {"Myanmar Kıyatı": "MMK"},
  {"Moğol Tugriki": "MNT"},
  {"Makao Patakası": "MOP"},
  {"Moritanya Ugiyası": "MRU"},
  {"Mauritius Rupisi": "MUR"},
  {"Maldiv Rufiyası": "MVR"},
  {"Malavi Kvaçası": "MWK"},
  {"Meksika Pesosu": "MXN"},
  {"Malezya Ringiti": "MYR"},
  {"Mozambik Meticalı": "MZN"},
  {"Nambiya Doları": "NAD"},
  {"Nijerya Nairası": "NGN"},
  {"Nikaragua Kordobası": "NIO"},
  {"Norveç Kronu": "NOK"},
  {"Nepal Rupisi": "NPR"},
  {"Yeni Zelanda Doları": "NZD"},
  {"Umman Riyali": "OMR"},
  {"Panama Balboası": "PAB"},
  {"Peruvian Nuevo Sol": "PEN"},
  {"Pagua Yeni Gine Kinası": "PGK"},
  {"Filipin Pesosu": "PHP"},
  {"Pakistan Rupisi": "PKR"},
  {"Polonya Zlotisi": "PLN"},
  {"Paraguay Guaranisi": "PYG"},
  {"Katar Riyali": "QAR"},
  {"Rumen Leyi": "RON"},
  {"Sırp Dinarı": "RSD"},
  {"Rus Rublesi": "RUB"},
  {"Ruanda Frangı": "RWF"},
  {"Suudi Arabistan Riyali": "SAR"},
  {"Solomon Adaları Doları": "SBD"},
  {"Seyşeller Rupisi": "SCR"},
  {"Sudan Sterlini": "SDG"},
  {"İsveç Kronu": "SEK"},
  {"Singapur Doları": "SGD"},
  {"Saint Selena Pound": "SHP"},
  {"Sierra Leone Leonesi": "SLE"},
  {"Sierra Leone Leonesi": "SLL"},
  {"Somali Şilini": "SOS"},
  {"Surinam Doları": "SRD"},
  {"Güney Sudan Lirası": "SSP"},
  {"Principe Dobrası": "STN"},
  {"Suriye Lirası": "SYP"},
  {"Svaziand Lilangenisi": "SZL"},
  {"Tayland Bahtı": "THB"},
  {"Tacikistan Somonisi": "TJS"},
  {"Türkmenistan Manatı": "TMT"},
  {"Tunus Dinarı": "TND"},
  {"Tonga Pa'angası": "TOP"},
  {"Trinidad ve Tobago Dola": "TTD"},
  {"Tuvaluan Doları": "TVD"},
  {"Yeni Tayvan Doları": "TWD"},
  {"Tanzanya Şilini": "TZS"},
  {"Ukrayna Grivnası": "UAH"},
  {"Uganda Şilini": "UGX"},
  {"ABD Doları": "USD"},
  {"Uruguay Peposu": "UYU"},
  {"Özbekistan Somu": "UZS"},
  {"Venezuela Bolivarı": "VES"},
  {"Vietnam Dongu": "VND"},
  {"Vanuatu Vatusu": "VUV"},
  {"Samoa Talası": "WST"},
  {"Orta Afrika CFA Frangı": "XAF"},
  {"Doğu Karayip Doları": "XCD"},
  {"Özel Çekme Hakkı": "XDR"},
  {"Batı Afrika CFA FRANGI": "XOF"},
  {"CFP Frangı": "XPF"},
  {"Yemen Riyali": "YER"},
  {"Güney Afrika Randı": "ZAR"},
  {"Zambiya Kvaçası": "ZMW"},
  {"Zimbabwean Doları": "ZWL"},
];
